backend:
  name: git-gateway
  repo: samet0demir/personal-website
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "projects"
    label: "Projeler"
    files:
      - file: "projects.json"
        label: "Tüm Projeler"
        name: "projects"
        fields:
          - label: "Projeler Listesi"
            name: "projects"
            widget: "list"
            fields:
              - label: "Başlık"
                name: "title"
                widget: "string"
              - label: "Süre"
                name: "duration"
                widget: "string"
              - label: "Problem"
                name: "problem"
                widget: "text"
              - label: "Çözüm"
                name: "solution"
                widget: "text"
              - label: "Sonuç"
                name: "outcome"
                widget: "text"
              - label: "Teknolojiler"
                name: "technologies"
                widget: "list"
              - label: "Link"
                name: "link"
                widget: "string"
